- modules/base-commerce/components/SfxCarousel.vue
- modules/demo-magento/magento/dynamicPages/CMS_PAGE.vue
- modules/demo-venia/magento/dynamicPages/CMS_PAGE.vue
- modules/theme-tailwind-magento/magento/cms/blocks/pb-button-item.vue
- modules/theme-tailwind-magento/molecules/ProductTile.vue
- modules/theme-tailwind/organisms/ProductCarousel.vue
- fix sfxCarousel slides inView & pagination reflecting slider
- fix ProductTile mising review & StockIndicators
- fix contact CMS_PAGE link styling and button href error
> Mobile fixes

- modules/demo-shopware/cypress/integration/category.js
- modules/theme-tailwind-shopware/cypress/support/pageObjects/Base.js
- modules/theme-tailwind-shopware/cypress/support/pageObjects/Category.js
- modules/theme-tailwind-shopware/cypress/support/pageObjects/Listing.js
- modules/theme-tailwind/organisms/CrossSellModal.vue
Added / fixed tests for category + added datacy for button on add to cart modal (continue-shopping])
> Add basic Cypress tests for Shopware

- modules/blog-magento/mappers/ToBlogPost.ts
- modules/catalog-magento/mappers/ToCategory.ts
- modules/catalog-magento/mappers/ToProduct.ts
- modules/cms-magento/mappers/ToCmsPage.ts
if meta.title in Magento product's admin is empty then use product name/category name
> Add fallback for meta titles

- docs/modules/graphql.md
**Added**
**Fixed**
**Removed**
> Add description about addFields utility into documentation inside GraphQL module

- modules/demo-px/cypress/integration/checkout.js
_There was an issue when doing one order and then another one, the environment crashed. This should help to prevent those crashes._
**Added**
- _A cypress test for two orders._
> Add test for two orders

- docs/.vitepress/config.js
- docs/advanced/event-bus.md
Pull request will add Event Bus section into documentation, because of a new support for event bus in SFX.
**Added**
- Event Bus section
> Add Event Bus documentation

- modules/create-storefront-x/template/px/modules/demo-px/pages/confirm-password-reset.vue
- modules/demo-magento/pages/customer/account/createPassword/index.vue
- modules/demo-px/pages/confirm-password-reset.vue
- modules/demo-px/pages/customer/account/createPassword/index.vue
- modules/theme-tailwind/templates/CreatePassword.vue
**Added**
**Fixed**
**Removed**
> Fixe reset password pages for native Magento

- modules/catalog-magento/composables/useProduct.ts
- modules/theme-tailwind-magento/molecules/CategoryButton.vue
- modules/theme-tailwind-magento/molecules/ProductTile.vue
- modules/theme-tailwind-magento/templates/BrandDetail.vue
- modules/theme-tailwind/molecules/HeaderMenu/FlyoutMenuSubCategory.vue
- modules/theme-tailwind/molecules/HeaderMenu/HamburgerMenuLink.vue
- modules/theme-tailwind/molecules/ProductGallery.vue
**Added**
**Fixed**
**Removed**
> Fix gallery for product variants to respect variant image

- modules/sitemap/server/routes/sitemap.xml.ts
- modules/vue-router-simple/sitemap/staticPages.ts
- modules/vue-router/sitemap/staticPages.ts
Sitemap.xml contains static pages
**Added**
- static pages to sitemap
> Add static pages to the sitemap

- modules/demo-px/config/googleAnalytics/GOOGLE_ANALYTICS_ID.ts
- modules/demo-shopware/config/googleAnalytics/GOOGLE_ANALYTICS_ID.ts
- storefront-x.px.config.js
- storefront-x.shopware.config.js
Removing GTM module
**Removed**
- GTM module
> Disable Google analytics on demos

- docs/getting-started/quick-start.md
- docs/integrations/magento.md
- modules/create-storefront-x/index.js
Improving docs wth list of all modules (paid and free) for full-featured SFX and Vanilla Magento
**Added**
- Improve docs and create script
> Improve docs for create script

- docs/getting-started/how-it-works.md
- docs/getting-started/simple-todo-app.md
When I went through the documentation, I have noticed several typos. So I have decided to correct them. I also want to practice creating of pull requests.
**Fixed**
Typos in the documentation
> Fix typos in the documentation

- modules/create-storefront-x/template/blank/tsconfig.json
- modules/create-storefront-x/template/magento/tsconfig.json
- modules/create-storefront-x/template/px/tsconfig.json
- modules/create-storefront-x/template/shopware/tsconfig.json
Tested in WebStorm and working 100%
tested in VS code (windows) and sometimes works, sometimes not. After research issue seems to be in VS code
> Fix TypeScript aliases for modules in node_modules

- cypress.config.ts
**Added**
**Fixed**
**Removed**
> Create Cypress videos and screenshots for failed tests

- modules/theme-tailwind-magento/magento/cms/blocks/pb-products.vue
Fix duplicity carousel on PB products
> Fix duplicated carousel in pb-products

- modules/create-storefront-x/template/px/modules/demo-px/pages/index.vue
- modules/theme-tailwind/molecules/BlogGrid.vue
- modules/vue/composables/useResource.ts
> Optimize fetching of BlogGrid on HP

- modules/theme-tailwind/templates/NotFound.vue
- modules/theme-tailwind/tests/playwright/ModuleCombinations.spec.js
> Add title for 404 page

- modules/cookie-script/vue/plugins/cookieScript.server.ts
fix async attr in cookie script
> Fix async attr in cookie script

- modules/catalog-labels-magento/graphql/fragments/Product.ext.ts
- modules/catalog-labels-magento/graphql/fragments/ProductInListing.ext.ts
refactor product labels fragment
> Improved product labels fragment extension

- modules/cms-magento/composables/cms/usePbBanner.ts
- modules/cms-magento/composables/cms/usePbBlock.ts
- modules/cms-magento/composables/cms/usePbRow.ts
- modules/theme-tailwind-magento/magento/cms/blocks/pb-banner.vue
add support for mobile images in PB banner
> Added support for mobile image in PB banner

- Dockerfile
**Added**
**Fixed**
**Removed**
> Fixed Dockerfile to serve on 0.0.0.0

- modules/cms-magento/composables/cms/usePbImage.ts
- modules/theme-tailwind-magento/magento/cms/blocks/pb-image.vue
fix rendering link around PB image
> Fixed rendering image with link in PageBuilder

- modules/create-storefront-x/template/magento/package.json
- modules/create-storefront-x/template/magento/storefront-x.config.js
- modules/create-storefront-x/template/px/package.json
- modules/create-storefront-x/template/px/storefront-x.config.js
- modules/speed-curve/stores/useRequestProfilerStore.ts
- modules/vue-pinia-shared-state/package.json
- modules/vue-pinia-shared-state/tests/playwright/SharedState.spec.js
- modules/vue-pinia-shared-state/vuePinia/plugins/sharedState.ts
- modules/vue-pinia/concepts/VuePiniaPlugins.js
- modules/vue-pinia/vue/plugins/vuePinia.ts
- yarn.lock
create pinia shared store plugin
Use pinia module
https://github.com/wobsoriano/pinia-shared-state
> Add pinia-shared-state module

- .github/workflows/mxcloud.yml
Added possibility to override cloud URL.
**Added**
**Fixed**
**Removed**
> Add possibility to override MxCloud url

- modules/speed-curve/vue/plugins/speedCurve.server.ts
**Added**
**Fixed**
**Removed**
> Fixed speedCurve memory leak on NodeJs

- modules/core/package.json
- modules/core/src/Serve.js
- modules/theme-tailwind/package.json
- yarn.lock
**Added**
**Fixed**
**Removed**
> Added unhandled rejection to SFX core Serve

- modules/core/src/Serve.js
**Added**
**Fixed**
**Removed**
> Added exit after global unhandled rejection
